//
// Generated by LLVM NVPTX Back-End
//

.version 7.5
.target sm_35
.address_size 64

	// .globl	_Z6vecAddPi

.visible .entry _Z6vecAddPi(
	.param .u64 _Z6vecAddPi_param_0
)
{
	.local .align 8 .b8 	__local_depot0[8];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .b32 	%r<2>;
	.reg .b64 	%rd<5>;

	mov.u64 	%SPL, __local_depot0;
	cvta.local.u64 	%SP, %SPL;
	ld.param.u64 	%rd1, [_Z6vecAddPi_param_0];
	cvta.to.global.u64 	%rd2, %rd1;
	cvta.global.u64 	%rd3, %rd2;
	st.u64 	[%SP+0], %rd3;
	ld.u64 	%rd4, [%SP+0];
	mov.u32 	%r1, 10;
	st.u32 	[%rd4], %r1;
	ret;

}
